FROM python:3.8

WORKDIR /app
COPY requirements.txt /app
RUN pip install -r requirements.txt
RUN python -c "import nltk; nltk.download('vader_lexicon')"

COPY . /app

CMD ["python", "docker_scraper.py"]