---
- name: Create directory to process twitter file
  file:
    path: "{{ remote_twitter_data_dir }}"
    state: directory

- name: Install unzip package
  ansible.builtin.apt:
    name: unzip
    state: present

- name: Install python library requirements
  ansible.builtin.pip:
    name: 
      - requests 
      - ijson
      - tweetnlp
      - nltk
      - pandas


- name: Copy twitterDataConfig file
  ansible.builtin.copy:
    src: "{{ local_twitter_data_dir }}/twitterDataConfig.py"
    dest: "{{ remote_twitter_data_dir }}/twitterDataConfig.py"

- name: Copy processor file
  ansible.builtin.copy:
    src: "{{ local_twitter_data_dir }}/processor.py"
    dest: "{{ remote_twitter_data_dir }}/processor.py"

- name: Copy bad-words file
  ansible.builtin.copy:
    src: "{{ local_twitter_data_dir }}/bad-words.txt"
    dest: "{{ remote_twitter_data_dir }}/bad-words.txt"

- name: Save twitter data from dropbox
  command: curl -L -o "{{ remote_twitter_data_dir }}/twitter-data.zip" https://www.dropbox.com/s/r6l4ke6h858bzph/twitter-huge.json.zip?dl=0

- name: Unzip twitter file
  command: unzip "{{ remote_twitter_data_dir }}/twitter-data.zip" -d "{{ remote_twitter_data_dir }}"
  
- name: Move twitter data to parent directory
  command: mv "{{ remote_twitter_data_dir }}/mnt/ext100/twitter-huge.json" "{{ remote_twitter_data_dir }}"

- name: Run twitter-data-processing script
  command: nohup python3 "{{ remote_twitter_data_dir }}/processor.py" &


