---
- name: Check if Docker Swarm has already been Initialized
  shell: docker node ls
  register: swarm_status
  ignore_errors: true
  tags: swarm

- name: Initialize Docker Swarm
  community.docker.docker_swarm:
    state: present
    default_addr_pool: "172.26.128.0/20" # subnet used in mrc
  when: swarm_status.rc != 0
  run_once: true
  tags: swarm

- name: Get the Manager join-token
  shell: docker swarm join-token --quiet manager
  register: manager_token
  tags: swarm

- name: Get the worker join-token
  shell: docker swarm join-token --quiet worker
  register: worker_token
  tags: swarm

- name: Install jsondiff package
  pip:
    name: jsondiff
    state: present