---
- name: Create directory to process sudo file
  file:
    path: "{{ remote_sudo_data_dir }}"
    state: directory

- name: Install unzip package
  ansible.builtin.apt:
    name: unzip
    state: present

- name: Install python library requirements
  ansible.builtin.pip:
    name: 
      - requests

- name: Copy sudo file
  ansible.builtin.copy:
    src: "{{ local_sudo_data_dir }}"
    dest: "{{ remote_sudo_data_dir }}"

- name: Unzip sudo file
  command: unzip "{{ remote_sudo_data_dir }}/sudo-data-processing/Sudo-Data.zip" -d "{{ remote_sudo_data_dir }}/sudo-data-processing"
    
- name: Install python library requirements
  ansible.builtin.pip:
    name: 
      - requests

- name: Run sudo-data-processing script
  command: python3 "{{ remote_sudo_data_dir }}/sudo-data-processing/sudo-processing.py"
