#
# Part of Assignment 2 - COMP90024 2023 Semester 1
# Cluster and Cloud Computing
# The University of Melbourne 
#
# Team 49:
#  * Navdeep Beniwal (1279517)
#  * Aditya Desu (1000447)
#  * Hieu (Nick) Huu (1329582)
#  * Jonathan Latti (1083374)
#  * Patricia Widjojo (913557)
#

---
- name: Create directory to process sudo file
  file:
    path: "{{ remote_sudo_data_dir }}"
    state: directory

- name: Install unzip package
  ansible.builtin.apt:
    name: unzip
    state: present

- name: Install python library requirements
  ansible.builtin.pip:
    name: 
      - requests

- name: Copy sudo file
  ansible.builtin.copy:
    src: "{{ local_sudo_data_dir }}"
    dest: "{{ remote_sudo_data_dir }}"

    
- name: Install python library requirements
  ansible.builtin.pip:
    name: 
      - requests

- name: Run sudo-data-processing script
  command: nohup python3 "{{ remote_sudo_data_dir }}/sudo-data-processing/sudo-processing.py" &
