---
- name: Copy sudo file
  ansible.builtin.copy:
    src: "{{ local_sudo_data_dir }}"
    dest: "{{ remote_sudo_data_dir }}"

- name: Install unzip package
  ansible.builtin.apt:
    name: unzip
    state: present

- name: Move Sudo-Income-data file
  ansible.builtin.command:
    cmd: mv "{{ remote_sudo_data_dir }}/Sudo-Income-data" "{{ remote_sudo_data_dir }}/.."
    
- name: Move Sudo-Rental-data file
  ansible.builtin.command:
    cmd: mv "{{ remote_sudo_data_dir }}/Sudo-Rental-data" "{{ remote_sudo_data_dir }}/.."
    
- name: Install python library requirements
  ansible.builtin.pip:
    name: 
      - pandas

- name: Run sudo-data-processing script
  command: nohup python3 "{{ remote_sudo_data_dir }}/sudo-data-processing/sudo-processing.py" &
