---
- name: Gather facts of remote host
  ansible.builtin.setup:
    gather_subset: all

- name: Install common dependencies
  tags: always
  become: yes
  ansible.builtin.apt:
    name: ['docker.io', 'apt-transport-https', 'build-essential', 'ca-certificates', 'curl', 'git', 'python3-dev', 'python3-pip', 'python3-setuptools', 'software-properties-common', 'unzip', 'vim']
    state: latest
    install_recommends: no
    update_cache: yes

# Configure vm user permission to access docker deamon
- name: add userpermissions
  become: yes
  shell: "usermod -aG docker ubuntu"

- name: reset ssh connection
  meta: reset_connection

- name: Update pip
  tags: always
  become: yes
  ansible.builtin.pip:
    name: ['pip']
    state: latest

# Uncomment the following code if python3-pip isn't already installed
# - name: install python package manager
#   apt:
#     name: python3-pip

# Installs Docker SDK
# --
# 
- name: install python sdk
  become: yes
  pip:
    name:
      - docker
      - docker-compose

- name: Add team's public keys to ssh authorized keys
  ansible.posix.authorized_key:
    user: ubuntu
    state: present
    key: '{{ item }}'
  with_file:
    - ../keys/team_public.key

