---
- name: Stop and remove couchdb container
  community.docker.docker_container:
    name: mrc_couchdb
    state: absent

- name: Remove CouchDB data volume
  community.docker.docker_volume:
    name: couchdb_data
    state: absent
