#
# Part of Assignment 2 - COMP90024 2023 Semester 1
# Cluster and Cloud Computing
# The University of Melbourne 
#
# Team 49:
#  * Navdeep Beniwal (1279517)
#  * Aditya Desu (1000447)
#  * Hieu (Nick) Huu (1329582)
#  * Jonathan Latti (1083374)
#  * Patricia Widjojo (913557)
#

---
- name: Stop and remove couchdb container
  community.docker.docker_container:
    name: mrc_couchdb
    state: absent

- name: Remove CouchDB data volume
  community.docker.docker_volume:
    name: couchdb_data
    state: absent
