- name: Deploy Mastodon Harvester Service 
  community.docker.docker_swarm_service:
    name: mastodon_harvester
    image: latti31/harvester_rebuild:latest
    mode: replicated
    replicas: 1
    state: present

- name: Deploy Node Backend Service 
  community.docker.docker_swarm_service:
    name: backend
    image: hieuhuung4/node_backend:latest
    publish:
      - published_port: 5000
        target_port: 5000
    mode: replicated
    replicas: 1
    state: present

- name: Deploy React Frontend Service 
  community.docker.docker_swarm_service:
    name: frontend
    image: hieuhuung4/react_frontend:latest
    publish:
      - published_port: 3000
        target_port: 3000
    mode: replicated
    replicas: 1
    state: present