#
# Part of Assignment 2 - COMP90024 2023 Semester 1
# Cluster and Cloud Computing
# The University of Melbourne 
#
# Team 49:
#  * Navdeep Beniwal (1279517)
#  * Aditya Desu (1000447)
#  * Hieu (Nick) Huu (1329582)
#  * Jonathan Latti (1083374)
#  * Patricia Widjojo (913557)
#

---
- name: Add Workers to the Docker Swarm
  community.docker.docker_swarm:
    state: join
    advertise_addr: "{{ ansible_host }}"
    join_token: "{{ hostvars[groups['master-server'][0]]['worker_token']['stdout'] }}"
    remote_addrs: [ "{{ hostvars[groups['master-server'][0]]['ansible_default_ipv4']['address'] }}:2377" ]
  tags: swarm