#
# Part of Assignment 2 - COMP90024 2023 Semester 1
# Cluster and Cloud Computing
# The University of Melbourne 
#
# Team 49:
#  * Navdeep Beniwal (1279517)
#  * Aditya Desu (1000447)
#  * Hieu (Nick) Huu (1329582)
#  * Jonathan Latti (1083374)
#  * Patricia Widjojo (913557)
#

---
- name: Install python library requirements
  ansible.builtin.pip:
    name: 
      - yfinance
      - numpy
      - matplotlib

- name: Copy finance file
  ansible.builtin.copy:
    src: "{{ local_finance_data_dir }}"
    dest: "{{ remote_finance_data_dir }}/single_json_object_eco_data.py"

- name: Run finance script to post data to couchDB
  command: python3 "{{ remote_finance_data_dir }}/single_json_object_eco_data.py" 
