#
# Part of Assignment 2 - COMP90024 2023 Semester 1
# Cluster and Cloud Computing
# The University of Melbourne 
#
# Team 49:
#  * Navdeep Beniwal (1279517)
#  * Aditya Desu (1000447)
#  * Hieu (Nick) Huu (1329582)
#  * Jonathan Latti (1083374)
#  * Patricia Widjojo (913557)
#

---
- name: Deploy CouchDb Container
  community.docker.docker_container:
    name: mrc_couchdb
    image: couchdb:3.3.2
    ports:
      - "5984:5984"
      - "4369:4369"
      - "9100-9200:9100-9200"
    env:
      COUCHDB_USER: "admin"
      COUCHDB_PASSWORD: "password"
      COUCHDB_SECRET: "a192aeb9904e6590849337933b000c99"
      ERL_FLAGS: "-setcookie \"a192aeb9904e6590849337933b000c99\" -name \"couchdb@{{ ansible_default_ipv4.address }}\" -kernel inet_dist_listen_min 9100 -kernel inet_dist_listen_max 9200"
      volumes:
        - couchdb_data:/opt/couchdb/data
      restart_policy: always