---
# Execute only to remove the CouchDb containers
# - name: Remove previous couchdb container
#   community.docker.docker_container:
#     name: mrc_couchdb
#     state: absent
#   register: removed

- name: Deploy CouchDb Container
  community.docker.docker_container:
    name: mrc_couchdb
    image: couchdb:3.3.2
    ports:
      - "5984:5984"
      - "4369:4369"
      - "9100-9200:9100-9200"
    env:
      COUCHDB_USER: "admin"
      COUCHDB_PASSWORD: "password"
      COUCHDB_SECRET: "a192aeb9904e6590849337933b000c99"
      ERL_FLAGS: "-setcookie \"a192aeb9904e6590849337933b000c99\" -name \"couchdb@{{ ansible_default_ipv4.address }}\" -kernel inet_dist_listen_min 9100 -kernel inet_dist_listen_max 9200"
      volumes:
        - couchdb_data:/opt/couchdb/data
      restart_policy: always

- name: Create twitter data database
  command: curl -X PUT "http://admin:password@localhost:5984/twitter_data_copy"

- name: Create mastodon data database
  command: curl -X PUT "http://admin:password@localhost:5984/mastodon_data_copy"

- name: Create sudo income data database
  command: curl -X PUT "http://admin:password@localhost:5984/sudo_income_data_copy"

  - name: Create sudo rental data database
  command: curl -X PUT "http://admin:password@localhost:5984/sudo_rental_data_copy"

