---
# TODO: Remove this network if not needed
- name: Create Network
  community.docker.docker_network:
    name: mrc_test_app_network

- name: Remove previous couchdb container
  community.docker.docker_container:
    name: mrc-couchdb
    state: absent
  register: removed

- name: Deploy CouchDb
  community.docker.docker_container:
    name: mrc_couchdb
    image: couchdb:3.3.2
    ports:
      - "5984:5984"
    networks:
      - name: mrc_test_app_network
    env:
      COUCHDB_USER: "admin"
      COUCHDB_PASSWORD: "password"
    volumes:
      - couchdb_data:/opt/couchdb/data
    restart_policy: always

- name: Create twitter_data database
  command: curl -X PUT "http://admin:password@localhost:5984/twitter_data"

- name: Create mastodon_data database
  command: curl -X PUT "http://admin:password@localhost:5984/mastodon_data"

- name: Create sudo_data database
  command: curl -X PUT "http://admin:password@localhost:5984/sudo_data"

