---
- name: Deploy Docker & Portainer
  hosts: all
  roles:
  - role: install-docker
  - role: install-portainer

- name: Initialize Docker SWARM
  hosts: master-server
  roles:
    - docker-swarm-init

- name: Add workers to the Docker SWARM
  hosts: worker-servers
  roles:
    - docker-swarm-add-worker

- name: Install jsondiff on master-server
  hosts: master-server
  tasks:
    - name: Install jsondiff package
      pip:
        name: jsondiff
        state: present