#
# Part of Assignment 2 - COMP90024 2023 Semester 1
# Cluster and Cloud Computing
# The University of Melbourne 
#
# Team 49:
#  * Navdeep Beniwal (1279517)
#  * Aditya Desu (1000447)
#  * Hieu (Nick) Huu (1329582)
#  * Jonathan Latti (1083374)
#  * Patricia Widjojo (913557)
#

- hosts: worker-server-2
  gather_facts: true
  vars:
    remote_sudo_data_dir: /home/ubuntu
    local_sudo_data_dir: ../sudo-data-processing
    remote_twitter_data_dir: /home/ubuntu/twitter-data-processing
    local_twitter_data_dir: ../twitter-data-processing
    remote_finance_data_dir: /home/ubuntu
    local_finance_data_dir: ./LiveEconomicData
  roles:
    - role: sudo-data-processing-ansible
    - role: add-finance-data
    - role: twitter-data-processing-ansible




