- hosts: all
  gather_facts: true
  become: yes
  roles:
    - role: common
    - role: install-docker
    - role: install-portainer
    - role: deploy-couchdb-containers

# - hosts: worker-server-2
#   gather_facts: true
#   vars:
#     remote_twitter_data_dir: /home/ubuntu/twitter-data-processing
#     local_twitter_data_dir: ../twitter-data-processing

#   roles:
#     - role: twitter-data-processing-ansible

- hosts: worker-server-1
  gather_facts: true
  become: yes
  vars:
    remote_sudo_data_dir: /home/ubuntu
    local_sudo_data_dir: ../sudo-data-processing
  roles:
    - role: sudo-data-processing-ansible





