---
# Configure vm user permission to run docker commmands
- name: add userpermissions
  shell: "usermod -aG docker ubuntu"

- name: reset ssh connection
  meta: reset_connection

# Installs Docker SDK
# --
# 
- name: install python package manager
  apt:
    name: python3-pip

- name: install python sdk
  become_user: "{{ ansible_env.SUDO_USER }}"
  pip:
    name:
      - docker
      - docker-compose